sunghwan_app/member/urls.py
from django.conf.urls import url, include
from member import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
]

sunghwan_app/sunghwan_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('member.urls', namespace='member')),
    url(r'^sunghwan/', include('sunghwan_park.urls', namespace='sunghwan')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sunghwan_app/sunghwan_park/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^movie/movie_list/$', views.movie_list, name='movie_list'),
    url(r'^movie/movie_update/$', views.movie_update, name='movie_update'),
    url(r'^movie/movie_detail/(?P<movie_id>\d+)', views.movie_detail, name='movie_detail'),
]

sunghwan_app/sunghwan_park/models.py
from django.db import models
import os
from django.conf import settings
from django.contrib.staticfiles.templatetags.staticfiles import static


# Create your models here.
class Movie(models.Model):
    # 제목, 감독, 장르, 한줄평, 개인 평점, 관람 날짜
    title = models.CharField(max_length=20, unique=True)
    director = models.CharField(max_length=20)
    genre = models.CharField(max_length=10)
    my_comment = models.TextField(default='')
    my_score = models.FloatField(default=0.0)
    watched_date = models.DateField()
    img_thumbnail = models.ImageField(upload_to='movie', blank=True, null=True)


    def __str__(self):
        return self.title

    def get_img_thumbnail(self):
        if self.img_thumbnail:
            return self.img_thumbnail.url
        else:
            return static('images/default-movie.png')

sunghwan_app/sunghwan_park/views/movie.py
from django.shortcuts import render, redirect, get_object_or_404
from openpyxl import load_workbook
from django.http import HttpResponse
from bs4 import BeautifulSoup
from sunghwan_park.models import Movie
from django.conf import settings
import os
import requests
from django.contrib import messages
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
# from sunghwan_app.custom_storages import StaticStorage
from sunghwan_park import tasks


# Create your views here.
__all__ = ['movie_list', 'movie_update',]


@login_required
def movie_list(request):
    if request.method == 'POST':
        order_criteria = request.POST['order-criteria']
        movies = Movie.objects.order_by('-'+order_criteria)
    else:
        movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'sunghwan_park/movie_list.html', context)


@staff_member_required
def movie_update(request):
    """
    This function is only for administrators.
    Compare the excel file to the existing Movie model instances.
    If any new movies are written, make new Movie model instances with a photo given by bs4.
    :param request:
    :return: none. Just Movie model update for the administrator.
    """
    # static_storage = StaticStorage()
    # wb = load_workbook(static_storage.open('others/박성환 영화 희망 및 관람 목록.xlsx'))

    # Check if a new movie is added

    tasks.movie_list_update(request)
    return redirect('member:index')


# 0 : watch_or_not, 1: title, 2: director, 3: genre,
# 4: my_comment , 5: my_score, 6: watched_date,

sunghwan_app/sunghwan_park/views/movie_detail.py
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Movie
from django.contrib import messages
from apis import naver_blog_post
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, UserManager

__all__ = ['movie_detail',]


@login_required
def movie_detail(request, movie_id):
    page = request.GET.get('page') or '1'

    try:
        movie = get_object_or_404(Movie, id=movie_id)
    except:
        messages.error(request, '그런 영화 또 없습니다.')
        return redirect('sunghwan:movie_list')

    else:
        blog_post_list = naver_blog_post(movie.title, page)
        context = {
            'movie': movie,
            'blog_post_list': blog_post_list
        }

    return render(request, 'sunghwan_park/movie_detail.html', context)

sunghwan_app/templates/sunghwan_park/movie_detail.html
{% extends 'root/base.html' %}

{% block content %}


<div class="container">
  <div id="full-container">
    <div class=" col-md-6 col-sm-12 panel movie-detail well">
      <div class="">
        <img src="{{ movie.get_img_thumbnail }}" alt="">
      </div>
      <div id="movie-data">
        <p><span class='movie-info'>제목 </span>: <span class='movie-real-info'>{{ movie.title }}</span></p>
        <p><span class='movie-info'>감독 </span>: <span class='movie-real-info'>{{ movie.director }}</span></p>
        <p><span class='movie-info'>장르 </span>: <span class='movie-real-info'>{{ movie.genre }}</span></p>
        <p><span class='movie-info'>나의 한 줄평 </span>: <span class='movie-real-info'>{{ movie.my_comment}}</span></p>
        <p><span class='movie-info'>내 점수는요! </span>: <span class='movie-real-info'>{{ movie.my_score }}</span></p>
        <p><span class='movie-info'>관람일자 </span>: <span class='movie-real-info'>{{ movie.watched_date }}</span></p>
      </div>

    </div>
    <div class="col-md-offset-1 col-md-5 col-sm-12 well blog-post">
    <h3>영화에 대한 반응</h3>
    <h5>*네이버 블로그 상위 포스트 기준</h4>
    <hr>


      <div class="panel-group" id="accordion">
      {% for post in blog_post_list %}

      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a style='color:green;' data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}">
            {{ post.0 }}
            </a>
          </h4>
        </div>

        <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse ">
          <div class="panel-body" >
            {{ post.1 }}
          </div>
        </div>
      </div>
      {% endfor %}
      </div>
      <ul class='pagination'>
        <li><a href="?page=1" class="btn btn-default" value="1">1</a></li>
        <li><a href="?page=2" class="btn btn-default" value="2">2</a></li>
        <li><a href="?page=3" class="btn btn-default" value="3">3</a></li>
        <li><a href="?page=4" class="btn btn-default" value="4">4</a></li>
        <li><a href="?page=5" class="btn btn-default" value="5">5</a></li>
      </ul>
    </div>

  </div>
</div>
</div>


{% endblock content %}

sunghwan_app/templates/sunghwan_park/movie_list.html
{% extends 'root/base.html' %}

{% block content %}


<div class="container">

  <div class="row">
    <div class="text-center movie-list-panel" style='position:relative'>
      <h2 style='display:inline-block'><abbr title="안녕하세요!">박성환</abbr>이 본 영화 목록 2015-2016</h2>

        <form action="" method='POST' class='order-by'>
          {% csrf_token %}
          <select name="order-criteria" id="" class="order-criteria">
            <option value="watched_date">최신 관람 순</option>
            <option value="my_score">높은 평점 순</option>
          <select>
          <button class="btn btn-default btn-sm" type="submit">Go!</button>
        </form>

    </div>
  </div>
  {% for message in messages %}
  <div class="panel">
    <p>{{message}}</p>
  </div>
  {% empty %}
  {% endfor %}

  {% for movie in movies %}
  <div class="col-md-3 col-sm-6">
    <div class="thumbnail">
      <a href="{% url 'sunghwan:movie_detail' movie_id=movie.id  %}?page=1"><img src="{{ movie.get_img_thumbnail }}" alt="" width="100%" style='height:150px'>
      </a>
      <h6 class='label-title'>{{movie.title|truncatechars:'16'}}</h6>
    {% comment %}

      <p>{{movie.director}}</p>
      <p>{{movie.my_score}}</p>
    {% endcomment %}

    </div>
  </div>

  {% empty %}
  <p>No movies available</p>

  {% endfor %}
</div>

{% endblock content %}