sunghwan_app/member/urls.py
from django.conf.urls import url, include
from member import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
]

sunghwan_app/sunghwan_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('member.urls', namespace='member')),
    url(r'^sunghwan/', include('sunghwan_park.urls', namespace='sunghwan')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sunghwan_app/sunghwan_park/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^movie/movie_list/$', views.movie_list, name='movie_list'),
    url(r'^movie/movie_update/$', views.movie_update, name='movie_update'),
    url(r'^movie/movie_detail/(?P<movie_id>\d+)', views.movie_detail, name='movie_detail'),
]

sunghwan_app/templates/root/base.html
{% load static from staticfiles %}


<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <title>반갑습니다.</title>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          <div class="navbar-header">
              {# 추후 추가 예정 #}
          </div>
          <ul class="nav navbar-nav navbar-right">
{#              <li><a href="#">item1</a></li> #}

              {% if request.user.is_authenticated %}

              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">박성환
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'sunghwan:movie_list' %}">영화 목록</a></li>
                  <li><a href="#">데이터</a></li>
                  <li><a href="#">???</a></li>
                </ul>
              </li>
              {% if user.is_sunghwan %}
              <li><a href="{% url 'sunghwan:movie_update' %}?next={{ request.path }}">영화 업데이트</a></li>
              {% endif %}
              <li><p style='margin: 15px 10px 0 10px' class='text-primary'>{{ request.user.nickname}}님 반갑습니다.</p></li>
              <li><a href="{% url 'member:logout' %}?next={{ request.path }}">Log out</a></li>
              {% else %}
              <li><a href="{% url 'member:login' %}?next={{ request.path }}">로그인</a></li>

              <li><a href="{% url 'member:signup' %}?next={{ request.path }}">회원가입</a></li>
              {% endif %}
          </ul>
      </div>
  </nav>

{% block content %}


{% endblock content %}

</body>
</html>

sunghwan_app/templates/root/index.html
{% extends 'root/base.html' %}
{% load static from staticfiles %}


{% block content %}
<h3>박성환 소개 페이지입니다.</h3>


<div>
    <img src="{% static 'images/장영실.jpg' %}" alt="장영실 사진">
    <p>이 사람이 누군지 맞추시면 소정의 상품이 있겠습니다.</p>
</div>

<p><span>Git hub</span><a href="https://github.com/shoark7">https://github.com/shoark7</a></p>
<p><span>facebook</span>
    <a href="https://www.facebook.com/sunghwan.park.75054">https://www.facebook.com/sunghwan.park.75054</a>
</p>



{% endblock content %}